from typing import Any, Dict, List, Optional

PROVIDER_TEMPLATES: List[Dict[str, Any]] = [
    {
        "provider": "openai",
        "label": "OpenAI",
        "description": "Model LLM dan reasoning untuk planner/agent.",
        "auth_hint": "OPENAI_API_KEY",
        "default_account_id": "default",
        "default_enabled": True,
        "default_config": {"base_url": "https://api.openai.com/v1", "model_id": "gpt-4o-mini"},
    },
    {
        "provider": "anthropic",
        "label": "Anthropic",
        "description": "Alternatif LLM untuk workflow agent.",
        "auth_hint": "ANTHROPIC_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.anthropic.com", "model_id": "claude-3-5-sonnet-latest"},
    },
    {
        "provider": "gemini",
        "label": "Google Gemini",
        "description": "LLM Gemini API untuk analisis tambahan.",
        "auth_hint": "GEMINI_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://generativelanguage.googleapis.com", "model_id": "gemini-1.5-pro"},
    },
    {
        "provider": "groq",
        "label": "Groq",
        "description": "Inference cepat untuk use-case latency rendah.",
        "auth_hint": "GROQ_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.groq.com/openai/v1", "model_id": "llama-3.1-70b-versatile"},
    },
    {
        "provider": "ollama",
        "label": "Ollama (Local LLM)",
        "description": "Provider model lokal via endpoint OpenAI-compatible Ollama.",
        "auth_hint": "OLLAMA_API_KEY (opsional, bisa diisi 'ollama')",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "http://localhost:11434/v1", "model_id": "qwen3:8b"},
    },
    {
        "provider": "github",
        "label": "GitHub",
        "description": "Akses repo, issue, PR, dan automasi development.",
        "auth_hint": "GITHUB_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.github.com"},
    },
    {
        "provider": "notion",
        "label": "Notion",
        "description": "Sinkronisasi knowledge base, docs, dan task notes.",
        "auth_hint": "NOTION_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.notion.com/v1", "notion_version": "2022-06-28"},
    },
    {
        "provider": "linear",
        "label": "Linear",
        "description": "Akses issue tracking dan workflow engineering.",
        "auth_hint": "LINEAR_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.linear.app/graphql"},
    },
    {
        "provider": "slack",
        "label": "Slack",
        "description": "Notifikasi dan command workflow ke channel Slack.",
        "auth_hint": "SLACK_BOT_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://slack.com/api"},
    },
    {
        "provider": "discord",
        "label": "Discord",
        "description": "Integrasi bot dan notifikasi channel Discord.",
        "auth_hint": "DISCORD_BOT_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://discord.com/api/v10"},
    },
    {
        "provider": "telegram_api",
        "label": "Telegram API",
        "description": "Akses API Telegram non-bridge untuk workflow kustom.",
        "auth_hint": "TELEGRAM_BOT_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.telegram.org"},
    },
    {
        "provider": "whatsapp_api",
        "label": "WhatsApp API",
        "description": "Integrasi WhatsApp Business API provider.",
        "auth_hint": "WHATSAPP_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://graph.facebook.com/v20.0"},
    },
    {
        "provider": "shopee",
        "label": "Shopee",
        "description": "Konektor riset produk dan harga marketplace Shopee.",
        "auth_hint": "SHOPEE_PARTNER_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://partner.shopeemobile.com", "region": "id"},
    },
    {
        "provider": "tokopedia",
        "label": "Tokopedia",
        "description": "Konektor katalog dan order Tokopedia.",
        "auth_hint": "TOKOPEDIA_API_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://fs.tokopedia.net", "region": "id"},
    },
    {
        "provider": "lazada",
        "label": "Lazada",
        "description": "Konektor API Lazada untuk data produk/order.",
        "auth_hint": "LAZADA_APP_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.lazada.co.id/rest", "region": "id"},
    },
    {
        "provider": "tiktok_shop",
        "label": "TikTok Shop",
        "description": "Konektor TikTok Shop untuk sinkron produk dan penjualan.",
        "auth_hint": "TIKTOK_SHOP_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://open-api.tiktokglobalshop.com", "region": "id"},
    },
    {
        "provider": "google_sheets",
        "label": "Google Sheets",
        "description": "Sinkron data tabel dari/ke Google Sheets.",
        "auth_hint": "GOOGLE_SERVICE_ACCOUNT_JSON",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"spreadsheet_id": "", "base_url": "https://sheets.googleapis.com/v4/spreadsheets"},
    },
    {
        "provider": "airtable",
        "label": "Airtable",
        "description": "CRUD record untuk operasi ringan seperti CRM/ops.",
        "auth_hint": "AIRTABLE_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.airtable.com/v0"},
    },
    {
        "provider": "facebook_graph",
        "label": "Facebook Graph",
        "description": "Akses halaman/posting/insight via Facebook Graph API.",
        "auth_hint": "FACEBOOK_ACCESS_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://graph.facebook.com/v20.0"},
    },
    {
        "provider": "instagram_graph",
        "label": "Instagram Graph",
        "description": "Insight dan media posting dari akun Instagram Business.",
        "auth_hint": "INSTAGRAM_ACCESS_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://graph.facebook.com/v20.0"},
    },
    {
        "provider": "tiktok_open",
        "label": "TikTok Open API",
        "description": "Integrasi data kreator/konten lewat TikTok Open API.",
        "auth_hint": "TIKTOK_ACCESS_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://open.tiktokapis.com/v2"},
    },
    {
        "provider": "youtube_data",
        "label": "YouTube Data",
        "description": "Data channel/video/trending dari YouTube Data API.",
        "auth_hint": "YOUTUBE_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://www.googleapis.com/youtube/v3"},
    },
    {
        "provider": "x_twitter",
        "label": "X / Twitter",
        "description": "Akses tweet, metrics, dan timeline API X.",
        "auth_hint": "X_BEARER_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.x.com/2"},
    },
    {
        "provider": "linkedin",
        "label": "LinkedIn",
        "description": "Posting dan insight via LinkedIn Marketing API.",
        "auth_hint": "LINKEDIN_ACCESS_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.linkedin.com/v2"},
    },
    {
        "provider": "serpapi",
        "label": "SerpAPI",
        "description": "Search engine result untuk riset cepat.",
        "auth_hint": "SERPAPI_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://serpapi.com", "engine": "google"},
    },
    {
        "provider": "perplexica",
        "label": "Perplexica (Self-Hosted Search)",
        "description": "Search AI engine self-hosted untuk riset web dengan sitasi.",
        "auth_hint": "PERPLEXICA_API_KEY (opsional, jika instance memakai auth)",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {
            "base_url": "http://localhost:3001/api/search",
            "focus_mode": "webSearch",
            "optimization_mode": "balanced",
        },
    },
    {
        "provider": "gpt_researcher",
        "label": "GPT Researcher",
        "description": "Engine riset mendalam untuk laporan multi-sumber.",
        "auth_hint": "GPT_RESEARCHER_API_KEY (jika pakai hosted API)",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.gpt-research.org/api/v1", "model_id": "gpt-4o-mini"},
    },
    {
        "provider": "apify",
        "label": "Apify",
        "description": "Menjalankan actor scraping terkelola dari dashboard.",
        "auth_hint": "APIFY_TOKEN",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.apify.com/v2"},
    },
    {
        "provider": "firecrawl",
        "label": "Firecrawl",
        "description": "Ekstraksi konten web terstruktur untuk agent.",
        "auth_hint": "FIRECRAWL_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.firecrawl.dev"},
    },
    {
        "provider": "supabase",
        "label": "Supabase",
        "description": "Akses PostgREST dan storage Supabase.",
        "auth_hint": "SUPABASE_SERVICE_ROLE_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://your-project.supabase.co/rest/v1", "schema": "public"},
    },
    {
        "provider": "pinecone",
        "label": "Pinecone",
        "description": "Vector database untuk retrieval dan semantic search.",
        "auth_hint": "PINECONE_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://api.pinecone.io", "index": ""},
    },
    {
        "provider": "qdrant",
        "label": "Qdrant",
        "description": "Vector search engine untuk embedding retrieval.",
        "auth_hint": "QDRANT_API_KEY",
        "default_account_id": "default",
        "default_enabled": False,
        "default_config": {"base_url": "https://your-qdrant-host:6333", "collection": ""},
    },
]

MCP_SERVER_TEMPLATES: List[Dict[str, Any]] = [
    {
        "template_id": "mcp_github",
        "server_id": "mcp_github",
        "label": "MCP GitHub",
        "description": "MCP server untuk akses repo dan issue GitHub.",
        "transport": "stdio",
        "command": "npx -y @modelcontextprotocol/server-github",
        "args": [],
        "url": "",
        "headers": {},
        "env": {"GITHUB_TOKEN": ""},
        "timeout_sec": 20,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_filesystem",
        "server_id": "mcp_filesystem",
        "label": "MCP Filesystem",
        "description": "MCP untuk baca/tulis file lokal.",
        "transport": "stdio",
        "command": "npx -y @modelcontextprotocol/server-filesystem",
        "args": ["."],
        "url": "",
        "headers": {},
        "env": {},
        "timeout_sec": 20,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_fetch",
        "server_id": "mcp_fetch",
        "label": "MCP Fetch",
        "description": "MCP HTTP fetch untuk ekstraksi konten web.",
        "transport": "stdio",
        "command": "npx -y @modelcontextprotocol/server-fetch",
        "args": [],
        "url": "",
        "headers": {},
        "env": {},
        "timeout_sec": 20,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_memory",
        "server_id": "mcp_memory",
        "label": "MCP Memory",
        "description": "MCP memory store untuk context jangka panjang.",
        "transport": "stdio",
        "command": "npx -y @modelcontextprotocol/server-memory",
        "args": [],
        "url": "",
        "headers": {},
        "env": {},
        "timeout_sec": 20,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_playwright",
        "server_id": "mcp_playwright",
        "label": "MCP Playwright",
        "description": "MCP browser automation untuk scraping terkontrol.",
        "transport": "stdio",
        "command": "npx -y @executeautomation/playwright-mcp-server",
        "args": [],
        "url": "",
        "headers": {},
        "env": {},
        "timeout_sec": 30,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_dbhub_stdio",
        "server_id": "mcp_dbhub",
        "label": "MCP DBHub (stdio)",
        "description": "MCP database universal (Postgres/MySQL/SQL Server/SQLite) via stdio.",
        "transport": "stdio",
        "command": "npx -y @bytebase/dbhub@latest",
        "args": ["--transport", "stdio", "--demo"],
        "url": "",
        "headers": {},
        "env": {},
        "timeout_sec": 45,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_browser_use_local",
        "server_id": "mcp_browser_use_local",
        "label": "MCP Browser Use (Local)",
        "description": "MCP browser automation lokal (stdio) dengan browser-use.",
        "transport": "stdio",
        "command": "uvx",
        "args": ["--from", "browser-use[cli]", "browser-use", "--mcp"],
        "url": "",
        "headers": {},
        "env": {"OPENAI_API_KEY": ""},
        "timeout_sec": 45,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_browser_use_cloud",
        "server_id": "mcp_browser_use_cloud",
        "label": "MCP Browser Use (Cloud)",
        "description": "MCP browser automation via endpoint cloud browser-use.",
        "transport": "http",
        "command": "",
        "args": [],
        "url": "https://api.browser-use.com/mcp",
        "headers": {"Authorization": "Bearer "},
        "env": {},
        "timeout_sec": 45,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_shopee_proxy",
        "server_id": "mcp_shopee_proxy",
        "label": "MCP Shopee Proxy",
        "description": "Contoh MCP HTTP untuk riset Shopee via service internal.",
        "transport": "http",
        "command": "",
        "args": [],
        "url": "https://api.example.com/mcp/shopee",
        "headers": {},
        "env": {},
        "timeout_sec": 20,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_tiktok_proxy",
        "server_id": "mcp_tiktok_proxy",
        "label": "MCP TikTok Proxy",
        "description": "MCP HTTP untuk analisis trend TikTok via service internal.",
        "transport": "http",
        "command": "",
        "args": [],
        "url": "https://api.example.com/mcp/tiktok",
        "headers": {},
        "env": {},
        "timeout_sec": 20,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_facebook_proxy",
        "server_id": "mcp_facebook_proxy",
        "label": "MCP Facebook Proxy",
        "description": "MCP HTTP untuk analisis data Facebook Graph via service internal.",
        "transport": "http",
        "command": "",
        "args": [],
        "url": "https://api.example.com/mcp/facebook",
        "headers": {},
        "env": {},
        "timeout_sec": 20,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_youtube_proxy",
        "server_id": "mcp_youtube_proxy",
        "label": "MCP YouTube Proxy",
        "description": "MCP HTTP untuk riset trend YouTube via service internal.",
        "transport": "http",
        "command": "",
        "args": [],
        "url": "https://api.example.com/mcp/youtube",
        "headers": {},
        "env": {},
        "timeout_sec": 20,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_firecrawl",
        "server_id": "mcp_firecrawl",
        "label": "MCP Firecrawl",
        "description": "MCP HTTP endpoint untuk crawl dan ekstraksi konten web.",
        "transport": "http",
        "command": "",
        "args": [],
        "url": "https://api.firecrawl.dev/mcp",
        "headers": {},
        "env": {"FIRECRAWL_API_KEY": ""},
        "timeout_sec": 30,
        "default_enabled": False,
    },
    {
        "template_id": "mcp_serpapi",
        "server_id": "mcp_serpapi",
        "label": "MCP SerpAPI",
        "description": "MCP HTTP endpoint untuk query search engine.",
        "transport": "http",
        "command": "",
        "args": [],
        "url": "https://serpapi.com/mcp",
        "headers": {},
        "env": {"SERPAPI_API_KEY": ""},
        "timeout_sec": 20,
        "default_enabled": False,
    },
]


def list_provider_templates() -> List[Dict[str, Any]]:
    return [dict(row) for row in PROVIDER_TEMPLATES]


def list_mcp_server_templates() -> List[Dict[str, Any]]:
    return [dict(row) for row in MCP_SERVER_TEMPLATES]


def get_provider_template(provider: str) -> Optional[Dict[str, Any]]:
    normalized = provider.strip().lower()
    for row in PROVIDER_TEMPLATES:
        if str(row.get("provider") or "").strip().lower() == normalized:
            return dict(row)
    return None


def get_mcp_server_template(template_id: str) -> Optional[Dict[str, Any]]:
    normalized = template_id.strip().lower()
    for row in MCP_SERVER_TEMPLATES:
        if str(row.get("template_id") or "").strip().lower() == normalized:
            return dict(row)
    return None
